### ISSUE TITLE
URL resolvability 

### ISSUE THREAD

**Issue by rajaram5** [sxzhang1201/assess-rdf-resource#6]
Do you consider a url is resolvable if you can find it in an ontology repository? Your tool tagged this URL `http://www.ebi.ac.uk/efo/EFO_0000785` not resolvable but I can query it via [ontobee SPARL](https://www.ontobee.org/sparql) endpoint. 
![url-resolvablity](https://user-images.githubusercontent.com/4365683/172431607-1d68f705-2240-48cd-a03c-e37793f8add1.png)

**Comment by sxzhang1201** [comment]
Thanks for the suggestion! The current focus of this tool is on the URI and the (first-hand) content retrieved (or parsed) from that URI.  

SPARQL is a nice way, but it does bring in some extra indirection. Strictly speaking, resolvability is simply an http(s) query, resulting in success or failure (e.g., 404). So maybe we can distinguish SPARQL resolvable and directly resolvable. :)
Besides, different endpoints can provide different information (sometimes even conflict and outdated), which would affect the quality assessment about consistency.

Here is the conference paper that ever utilized the old-versioned tool that incorporated SPARQL: 
https://ebooks.iospress.nl/doi/10.3233/SHTI210825.
